### PR TITLE
Feature queries from file

### LINKED ISSUE #1: binary replication montitoring metrics
Hi,

I'm interested in using your exporter to monitor a streaming replication cluster. However it looks like it's missing a few metrics, specifically these would be interesting:

```
pg_is_in_recovery()
pg_last_xact_replay_timestamp()
pg_last_xlog_replay_location()
pg_last_xlog_receive_location()
pg_current_xlog_location()
pg_is_in_backup()
```

from http://www.postgresql.org/docs/9.4/static/functions-admin.html

### PR DESCRIPTION
**Pull request by noushi**
Hi @wrouesnel ,

This PR adds support for custom queries in an external YAML file.

SHOW variables are not supported yet.

It should help close #1 .

I've deployed it yesterday and we're successfully getting metrics from our 54 Postgres replicas.

### CODE REVIEW

**Comment by wrouesnel** [comment]
Very nice! I'll review and merge asap.

**Comment by noushi** [comment]
:+1: Thanks!
It'll probably need some variable and function renaming to fit the Go standard.
I'll do it asap.

**Comment by noushi** [comment]
Done. 
I'll wait for your review.

Btw, the yaml metric is a custom one we use, so it would probably make sense to update queries.yaml to have names that closely reflect the Pg [admin functions](http://www.postgresql.org/docs/9.4/static/functions-admin.html)

**Comment by ncabatoff** [comment]
I found an issue with noushi's PR so I created a PR on it (https://github.com/noushi/postgres_exporter/pull/1), not sure if that's the right way to do it?  Just thought I'd mention it here so that you incorporate the fix when you merge this PR, in case noushi hasn't done so himself.

**Comment by noushi** [comment]
Thank you @wrouesnel @ncabatoff .

**Pull request merged**
