### PR TITLE
Add retries to getServer()

### PR DESCRIPTION
**Pull request by dmolik**
Some backstory
==============

I was attempting to use postgres_exporter with the official Docker
container (https://hub.docker.com/_/postgres) In a Kubernetes
StatefulSet, with a side-car configuration, but found that I wasn't able
to connect even with sharing the Postgres Unix listening socket, between
both containers. After copying the container over to an Alpine base I
quickly found out that the postgres_exporter was actually starting
before the main Postres container had dropped the unix socket onto the
file system, a quick work around is to write a bash for loop checking
for the existence of a unix socket, however this would require
maintaining a container, besides other users may find retries useful on
startup.

Implementation
==============

All changes are made to the getServer function and variables are
local, I was unsure if it was worth adding command line switches but
this would allow for a more sophisticated backOff loop in the future.

Hope this help, and let me know if you would like me to changes
anything.

### CODE REVIEW

**Comment by dmolik** [comment]
I went for a run and realized I introduced a bug. I'm going to move the error count evaluation to the top of the loop

**Comment by dmolik** [comment]
Squashed

**Comment by dmolik** [comment]
Squashed, and passing tests and linter!

**Comment by wrouesnel** [comment]
Feels like it should be a configurable, but it solves a problem.

**Comment by dmolik** [comment]
Perhaps it should be however some sort of error backoff would be appropriate as well.

**Pull request merged**
