### PR TITLE
fixed version parsing for Windows and EnterpriseDB

### LINKED ISSUE #142: Version check doesn't handle EnterpriseDB version strings
Log:
`level=warning msg="Proceeding with outdated query maps, as the Postgres version could not be determined: Error parsing version string: Could not find a postgres version in string: EnterpriseDB 9.6.5.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit\n" source="postgres_exporter.go:1019"`

Version check regexp should accept an optional fourth part.

### PR DESCRIPTION
**Pull request by marcinbudny**
Fixes #142

### CODE REVIEW

**Comment by marcinbudny** [comment]
I'm new to golang and I'm not really sure why the build fails. The output at one point says:
```
postgres_exporter_test.go:1::warning: file is not gofmted with -s (gofmt)
make: *** [style] Error 1
The command "make all" exited with 2.
```
However when I run `go fmt` locally, files are not changed. The output does not specify any other  broken rule. Any help?

**Comment by wrouesnel** [comment]
@marcinbudny run "make fmt" instead.

**Comment by marcinbudny** [comment]
@wrouesnel  That helped, thanks

**Comment by wrouesnel** [comment]
Looks great! Appreciate the tests - merging.

**Pull request merged**
