### PR TITLE
Support SCRAM-SHA-256

### PR DESCRIPTION
**Pull request by wlfshmn**
Updated lib/pg driver to 1.2.0 in order to support stronger SCRAM-SHA-256 authentication. This drops support for Go < 1.11 and PostgreSQL < 9.4.

### CODE REVIEW

**Comment by wlfshmn** [comment]
Intended as a minimal fix for #231 which was blocking us from monitoring new servers.

**Comment by RobAtticus** [comment]
Would love to see this in as soon as possible -- thanks @wlfshmn

**Comment by iand** [comment]
We're currently maintaining an internal fork with just this commit added. It would be great to get this updated since the version of lib/pq currently bundled is two years old @wrouesnel

**Comment by RobAtticus** [comment]
Hi @wrouesnel, any idea if this can be merged soon?

**Comment by wrouesnel** [comment]
Merged.

**Comment by Neustradamus** [comment]
@wlfshmn and others: Thanks a lot for all about SCRAM.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Pull request merged**
