### PR TITLE
Add a build info metric

### PR DESCRIPTION
**Pull request by SuperQ**
Add a standard Prometheus build info metric to make monitoring rollouts
easier.

### CODE REVIEW

**Comment by SuperQ** [comment]
I'm not sure the best way to add test coverage for the additional code.

**Comment by wrouesnel** [comment]
I'm content with the test coverage, but could you rebase the vendoring changes into one commit?

**Comment by SuperQ** [comment]
Sure, no problem

**Comment by SuperQ** [comment]
Fast-forward rebased and swashed the vendor change.

**Pull request merged**
