### PR TITLE
Added metrics for locks, pg_stat_replication and pg_stat_activity

### PR DESCRIPTION
**Pull request by knutemann**
Added metrics for locks, pg_stat_replication and pg_stat_activity.

Added support to be able to collect metrics from more complex queries.

Added guide in README.md if you want to run as non-superuser.

### CODE REVIEW

**Comment by wrouesnel** [comment]
This looks good! Could you run gofmt over the file and squash it into 1 commit.

**Comment by knutemann** [comment]
Thank you for responding!

gofmt did change quite a few lines. It looks better now.

**Comment by 0x46616c6b** [comment]
+1

**Comment by wrouesnel** [comment]
Finally an opportunity to sit down and test it - all looks good so merged. This also closes #1 is believe.

**Pull request merged**
