### PR TITLE
add support for secrets files

### PR DESCRIPTION
**Pull request by matthias-kloeckner**
this introduces new env variables for user name, password and uri. more importantly user name and password can also be read from files - this is needed to securely pass secrets to the docker container by just mounting these files.

new variables:
DATA_SOURCE_USER
DATA_SOURCE_USER_FILE
DATA_SOURCE_PASS
DATA_SOURCE_PASS_FILE
DATA_SOURCE_URI

### CODE REVIEW

**Comment by hartmut-pq** [comment]
+1 would like to see secrets supported, too!

**Comment by matthias-kloeckner** [comment]
added some tests and fixed the makefile. sorry for the amount of commits - I needed some test runs on travis to understand the real problem.

**Comment by matthias-kloeckner** [comment]
@wrouesnel 
anything still missing here?

**Comment by wrouesnel** [comment]
No this is looking good. I'll give it a closer inspection tonight and merge it hopefully.

**Pull request merged**
