### PR TITLE
bash style fixes

### PR DESCRIPTION
**Pull request by tamsky**

### CODE REVIEW

**Comment by wrouesnel** [comment]
I'm all for this PR, but I'd be happier if there was an associated linter or tool references which is making/can enforce these recommendations.

**Comment by tamsky** [comment]
I was doing it by hand.

Since you mentioned it, and I agreed it's a good idea.
I fired up https://github.com/koalaman/shellcheck and have started following its suggestions.

I'll report back shortly with a green build and a make target.

**Comment by tamsky** [comment]
@wrouesnel this is ready for review.

I've added the shellcheck linter to the Makefile.
I've updated shell scripts to address findings and harmonize styles across scripts.

**Comment by tamsky** [comment]
> Could you rebase and squash this down to a few logical commits?

Rebased.
Also, "Allow edits from maintainers." is enabled for this PR.

**Comment by wrouesnel** [comment]
Tried merging this but the scripts have deviated a lot. The improvements will be incorporated as a fresh set of changes.

**Pull request closed without merging**
