### PR TITLE
Refactor exporter so that it can be used as a library.

### PR DESCRIPTION
**Pull request by tamalsaha**
We are using the Postgres exported in our project as a library. This pr refactors the exporter to a `collector` subpackage so that it can be used as a library.

### CODE REVIEW

**Comment by wrouesnel** [comment]
I like this commit. I'll refactor it in the next few days to fit the new repository structure just rolled out, but great work!

**Comment by wrouesnel** [comment]
Okay so looking into this further, I'm merging the overall idea but it's very conditional - it's a supremely hacky way to use it as a library and should be regarded as unstable. The interface is going to be aggressively changed in the near future to factor out all the global variables which make it pretty unsafe to use as is.

**Comment by tamalsaha** [comment]
@wrouesnel, sounds good to me with your caveat. For now we are vendoring. Looking forward to stable state.

**Comment by hbagdi** [comment]
@wrouesnel friendly ping for any update on this.

**Comment by wrouesnel** [comment]
Working on it. There's a fair bit of refactoring to make it sensible (and to support multiple exporter instances sanely).

I'm also pulling the built-in queries out to a YAML file format so everything can be overridden.

**Comment by wrouesnel** [comment]
What am I saying? This Github! - the work libraryize work is happening on this branch here: https://github.com/wrouesnel/postgres_exporter/tree/libraryize_mk2

**Comment by tamalsaha** [comment]
@wrouesnel, wondering what are the plans on this one.

**Comment by hbagdi** [comment]
@wrouesnel any update on this? This would be an awesome feature to monitor multiple Postgres instances using a single exporter. Appreciate your efforts, thank you!

**Pull request closed without merging**
